# Generated by Django 5.1.4 on 2025-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='telefon_nomer',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
